"""add email_notifications table

Revision ID: 98df303730fa
Revises: a3b4c5d6e7f8
Create Date: 2026-08-27 16:38:12.866613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '98df303730fa'
down_revision: Union[str, None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_notifications_instance_id'), 'email_notifications', ['instance_id'], unique=False)
    op.create_index(op.f('ix_email_notifications_notification_type'), 'email_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_email_notifications_recipient_user_id'), 'email_notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_email_notifications_status'), 'email_notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_notifications_status'), table_name='email_notifications')
    op.drop_index(op.f('ix_email_notifications_recipient_user_id'), table_name='email_notifications')
    op.drop_index(op.f('ix_email_notifications_notification_type'), table_name='email_notifications')
    op.drop_index(op.f('ix_email_notifications_instance_id'), table_name='email_notifications')
    op.drop_table('email_notifications')
    # ### end Alembic commands ###